export const ROUTES = {
  public: {
    home: "/",
    explore: "/explore",
    providerDetail: (id: string) => `/providers/${id}`,
  },
  auth: {
    login: "/login",
    registerClient: "/register/client",
    registerProvider: "/register/provider",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    verifyEmail: "/verify-email",
  },
  client: {
    dashboard: "/dashboard",
    bookings: "/bookings",
    bookingDetail: (id: string) => `/bookings/${id}`,
    book: (providerId: string) => `/book/${providerId}`,
    payments: "/payments",
    saved: "/saved",
    notifications: "/notifications",
    profile: "/profile",
  },
  provider: {
    dashboard: "/provider/dashboard",
    bookings: "/provider/bookings",
    bookingDetail: (id: string) => `/provider/bookings/${id}`,
    services: "/provider/services",
    availability: "/provider/availability",
    portfolio: "/provider/portfolio",
    earnings: "/provider/earnings",
    notifications: "/provider/notifications",
    settings: "/provider/settings",
  },
  admin: {
    dashboard: "/dashboard",
    users: "/users",
    userDetail: (id: string) => `/users/${id}`,
    bookings: "/bookings",
    payments: "/payments",
    reviews: "/reviews",
    providers: "/providers",
  },
} as const;
